### ISSUE TITLE
Expanding from an autocmd

### ISSUE THREAD

**Issue by eemed** [Jorengarenar/miniSnip#11]
I am using skeleton files to template certain filetype files. I would like to move these to use miniSnip functionality for vimscript evaluation. Is it possible to trigger a certain snippet from an `autocmd BufNewFile`?

**Comment by Jorengarenar** [comment]
Yes, it is possible by combining `:h :normal` and `:h i_CTRL-R_=`. For example, to insert snippet `hello` into C file:
```vim
autocmd BufNewFile *.c exec "norm! i" . 'hello' . "\<C-r>=miniSnip#trigger()\<CR>"
```
