### ISSUE TITLE
Forward & Backlash in snippet value do not expand reference snippet properly

### ISSUE THREAD

**Issue by jmzagorski** [Jorengarenar/miniSnip#19]
I have not had the opportunity to look into this yet, but I thought I would let you know about an issue I am running into. Whenever my snippet value has a \ or a /, the reference snippet does not expand properly. I included the animation to show you. My plugin configuration is below as well. Are you able to replicate this issue?

![2021-08-11_13-28-07](https://user-images.githubusercontent.com/8404957/129075626-5bf614c7-5448-45c2-9f57-721b580fb20b.gif)

```vimscript
let g:miniSnip_dirs=[ $MYVIMRCPATH . '/after/mysnippets' ]
let g:miniSnip_ext="snippet"
let g:miniSnip_opening="${"
let g:miniSnip_closing="}"
let g:miniSnip_delimChg="`"
```

**Comment by jmzagorski** [comment]
Just tested our the new commit, and it works as expected. Thank you for the help. 👍

**Comment by rsmith31415** [comment]
@jmzagorski I apologize if this is quite obvious, but how do you create snippets with a backslash? I thought the filename of the snippet is used as the token to be expanded, so I can't create a file called `/.snip` and `\.snip` (or for that matter, `\\.snip`, `\\\.snip`) is not triggered after pressing tab:

```
╰─ → $ tree all
all
├── arrow.snip
├── check.snip
├── \.snip
└── trademark.snip
```

**Comment by Jorengarenar** [comment]
@rsmith31415 The issue was about slashes in values for placeholders, not snippet names

**Comment by Jorengarenar** [comment]
@rsmith31415 Unfortunately, that would require too much changes

**Comment by rsmith31415** [comment]
That's fair. Thank you for the response :+1:
