### ISSUE TITLE
<C-x><C-u> opens split window as preview

### ISSUE THREAD

**Issue by rsmith31415** [Jorengarenar/miniSnip#22]
First of all, thank you very much for this great plugin!

I noticed that `i_<C-x><C-u>` shows the snippets for the associated filetype, but it is also open a split as shown below:

![screenshot-220706-2222-16](https://user-images.githubusercontent.com/599274/177683793-6b1db966-12c2-453b-83ed-cd5f9b8398dc.png)

This is my configuration:

```
let g:miniSnip_opening = '{{'
let g:miniSnip_closing = '}}'
let g:miniSnip_local = 'miniSnip'
```

I'm not sure if this behavior was enabled by default on purpose, however, I was wondering if it can be disabled. I don't really need a preview, so it would be enough to see the suggestions in the pop up menu as usual.

Thanks!

**Comment by Jorengarenar** [comment]
Could you share your vimrc? Because this behaviour is not intended

**Comment by Jorengarenar** [comment]
Ah, OK, so it's not problem with plugin; it's default Vim behaviour.  
You need to remove `preview` from `completeopt` (`set completeopt-=preview`)

<sup>PS. Vundle is considered quite outdated; consider switching to native `:packadd` or vim-plug</sup>

**Comment by rsmith31415** [comment]
@Jorengarenar I didn't know this option was enabled by default (`menu,preview`). That certainly fixed it. I guess most people have a different  value for `completeopt`.
