### ISSUE TITLE
Unknown function: miniSnip#trigger

### ISSUE THREAD

**Issue by TheTaoOfPhil** [Jorengarenar/miniSnip#28]
# The Problem

The current version of **miniSnip** works just as it should on my arch and manjaro machines. However, only on macos 
(Ventura 13.2.1), when I try to insert a snip, I get this error: 

```
   E117: Unknown function: miniSnip#trigger
```

I am installing as follows: 

```
  Plug 'Jorengarenar/miniSnip'
```

The only configuration settings are:

```
  let g:miniSnip_trigger = '<C-g>'
  let g:miniSnip_dirs = [  '~/.vim/minisnip_modern' ]
```

# Possible Root Cause

I suspect the problem has something to with the mixed-case name of ``miniSnip``. In its typical configuration, macos *preserves* case, but it does not differentiate a mixed case from all lower case file name. 

This just sounds so strange that I had to run the following experiment:

On manjaro:

```
echo "doc 1" > doc.txt
echo "doc 2" > Doc.txt
ls
  doc.txt  Doc.txt
cat doc.txt
  doc 1
cat Doc.txt
  doc 2
```

On macos:

```
  echo "doc 1" > doc.txt
  echo "doc 2" > Doc.txt
  ls
    doc.txt
  cat doc.txt
    doc 2
```

As you would expect, on a real linux system, ``doc.txt`` and ``Doc.txt`` are completely different files, and so both are preserved and have their own content. On macos, ``doc.txt`` and ``Doc.txt`` are seen as the same file. Thus we end up with only one file, and it has the content of the second command (macos overwrote the first file)

I don't know enough about how vim plugins are structured to explain the precise mechanism for the failure to find the function, but the case-insensivity on macos strikes me as a possible culprit.

  ÷÷÷

**Comment by Jorengarenar** [comment]
Could you try with the branch [`lowercase`](https://github.com/Jorengarenar/miniSnip/tree/lowercase)?

**Comment by TheTaoOfPhil** [comment]
Sorry, that did not do the trick: still getting the same error.
(I did verify that I am on the ``lowercase`` branch).

**Comment by Jorengarenar** [comment]
What's the output of `:version`, `:scriptnames` and `:echo &rtp`?  
Could you share your whole Vim config?  
Are you able to call the function manually (`:call miniSnip#trigger()`)?

**Comment by TheTaoOfPhil** [comment]
I am attaching a file with the output of all commands, and ``.vimrc`` is also appended.
[commands.txt](https://github.com/Jorengarenar/miniSnip/files/10922210/commands.txt)

**Comment by Jorengarenar** [comment]
Let's try explicitly (e.g. at the end of vimrc) sourcing the file with `:so ~/.vim/bundle/miniSnip/autoload/miniSnip.vim`

**Comment by Jorengarenar** [comment]
To be sure, may you reboot the machine and check if the problem still occurs then?
If it wont happen again, then we can only assume it was caused by some "cosmic will"

**Comment by TheTaoOfPhil** [comment]
Yeah, rebooted, and it still works. Sigh. I'm convinced there is an explanation for this. But not worth obsessing over. 

Thanks again for all your help. I am enjoying this tool!
--Phil
