### ISSUE TITLE
Unexpected indent on last line of snippet

### ISSUE THREAD

**Issue by jmcantrell** [Jorengarenar/miniSnip#31]
The following snippet:

```
? tag
$ `{{` `}}`
<{{name}}{{}}>
	{{+}}
</{{~1}}>
```

Leaves the last line indented:

```
<foo disabled>
  text
  </foo>
```

I thought it might be autoindent, but turning that off didn't seem to affect it, and nothing seemed relevant in the formatoptions. Any ideas?

**Comment by Jorengarenar** [comment]
This is snippet for HTML, right? The default `indentexpr` for this filetype doesn't handle unknown/custom tag names very well

**Comment by jmcantrell** [comment]
Ah, that makes sense
