### ISSUE TITLE
Hope minisnip add selection region

### ISSUE THREAD

**Issue by Angluca** [Jorengarenar/miniSnip#34]
![222](https://github.com/Jorengarenar/miniSnip/assets/156404/15cf05a9-0a9c-4798-b471-0f7fc05c1a00)
this plugin  https://github.com/mbbill/code_complete is good and tiny, But not good for building our language snip libs and not update now.
Maybe minisnip can borrow its advantages

**Comment by Angluca** [comment]
https://github.com/Jorengarenar/miniSnip/pull/35
Like it!

**Comment by Angluca** [comment]
https://github.com/Jorengarenar/miniSnip/pull/37
Add selection region now :)

**Comment by Jorengarenar** [comment]
Please, update the issue with **proper description** - few **paragraphs**, not few words

**Comment by Angluca** [comment]
I'm a newbie T. T
I can only look forward to the author's update
Hope minisnip will be better in the future .

**Comment by Jorengarenar** [comment]
Well, since I still have no clue what's all of this about, I'm closing the issue.
