### ISSUE TITLE
After latest commit (11bc4fd), snippet name is left behind after expanding

### ISSUE THREAD

**Issue by jmcantrell** [Jorengarenar/miniSnip#40]
If `foo.snip` contains:

```
test
```

And the buffer looks like (`*` is the cursor position):

```
foo*
```

After the latest commit ([11bc4fd](https://github.com/Jorengarenar/miniSnip/commit/11bc4fd3e6ad37938338178592fbd0a87877f6b7)), triggering the snippet expansion results in:

```
footest*
```

When it should be:

```
test*
```

**Comment by Jorengarenar** [comment]
Thanks! It was actually 16d1d67 and I didn't notice because I have `set ve=all` in my config
