### ISSUE TITLE
Snippets that contain an indent do not expand to spaces when `'expandtab'` is set

### ISSUE THREAD

**Issue by jmcantrell** [Jorengarenar/miniSnip#41]
If a snippet file `foo.snip` contains something like (where `<tab>` is a tab character):

```
<tab>test
```

And the buffer contains (where `*` is the cursor position):

```
foo*
```

And `'expandtab'` is set, the buffer will be the following after expansion:

```
<tab>test
```

Where it should be (given a `'shiftwidth'` setting of `4`:
```
    test
```

**Comment by Jorengarenar** [comment]
Weird, b99bc0e should be addressing exactly that scenario

**Comment by jmcantrell** [comment]
For some reason, I did not get that commit when I last pulled. It is expanding the tabs now, but they are expanded to the value of `'tabstop'` and not '`shiftwidth`'.
