### ISSUE TITLE
When expanding <tab>'s, `'smarttab'` is not respected

### ISSUE THREAD

**Issue by jmcantrell** [Jorengarenar/miniSnip#42]
When expanding snippets with `<tab>` indents, they are expanded using the value of `'tabstop'`, regardless of the `'smarttab'` setting.

After reading the help on `'ins-smarttab'`, it appears that `<tab>` should use `'shiftwidth'` to expand `<tab>`'s when `'smarttab'` is on (it is for me), and `'tabstop'` otherwise.

**Comment by jmcantrell** [comment]
It looks like `'paste'` resets `'smarttab'`, which is being turned on just before inserting the snippet.

**Comment by Jorengarenar** [comment]
Eh, fix one bug and a dozen others popup. I've replaced setting `paste` with custom function. Should be better now.
