### ISSUE TITLE
Final placeholder @{}@ does not function as expected when g:miniSnip_opening & g:miniSnip_closing are changed

### ISSUE THREAD

**Issue by jmzagorski** [Jorengarenar/miniSnip#5]
First off, great job on a simple yet elegant snippet solution! I had ultisnips for a while, but never used all of its features so i removed it from my vimrc.

I was not sure the best way to fix this issue. I changed the config to the below settings:

```vimscript
let g:miniSnip_opening="{"
let g:miniSnip_closing="}"
```

and believe the `s:final_pattern` logic never fires because an exception is not thrown within this try/catch https://github.com/Jorengarenar/miniSnip/blob/master/autoload/miniSnip.vim#L114 because `@{}@` is a valid placeholder with the new opening/closing configuration.

**Comment by jmzagorski** [comment]
Also, there does seem to be different behaviors when you change the finalOp/finalEd too:

```
let g:miniSnip_finalOp="{"
let g:miniSnip_finalEd="}"
```

In the default plugin configuration, my curosr stays where the final placeholder is, and pressing tab inserts an actual tab in the buffer, but when changed to the config above, it jumps back to the first placeholder and completes.

**Comment by Jorengarenar** [comment]
During refactoring, I've decided to resign from final delimiters altogether. Instead there is now final tag (`:h g:minisnip_finalTag`). Let me know how does it work

**Comment by jmzagorski** [comment]
Thank you!. I changed over to the new final placeholder and it seems to be working fine on my first few tests.

**Comment by Jorengarenar** [comment]
I'm glad then
