### ISSUE TITLE
Space after expansion

### ISSUE THREAD

**Issue by andreasKroepelin** [Jorengarenar/miniSnip#9]
Hi,
first of all, thanks for letting me get rid of UltiSnips.

I have found the following issue:
Whenever I expand a snippet, a space is inserted after the expansion.
This is especially annoying as it constantly produces trailing white space.

Is this a known thing? If so, how can I avoid it?

Thanks!

**Comment by Jorengarenar** [comment]
If I understand correctly, you have snippet `foo`, which expands to `foobar`. If you have `foo|abc` (where `|` symbolizes cursor) and expand it, the the result is `foo abc`?

**Comment by andreasKroepelin** [comment]
Wow, thanks for your commitment! It works flawlessly now.
